version: "2"
run:
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - godox
    - wsl
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - '!**/*_a _file.go'
          allow:
            - Scruticode/src/core
            - Scruticode/src/shared
            - Scruticode/src/main.go
          deny:
            - pkg: math/rand$
              desc: use math/rand/v2
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    unused:
      field-writes-are-uses: false
      post-statements-are-reads: true
      exported-fields-are-used: false
      parameters-are-used: false
      local-variables-are-used: false
      generated-is-used: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: ^could not import
      - path: (.+)\.go$
        text: '^: #'
      - path: (.+)\.go$
        text: imported and not used$
      - path: (.+)\.go$
        text: 'undefined: .*'
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: 'undefined: .*'
