## https://golangci-lint.run/usage/configuration/

repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-imports ## go install golang.org/x/tools/cmd/goimports@latest
      - id: golangci-lint ## yay -S golangci-lint
        # pass_filenames: false ## https://github.com/pre-commit/pre-commit/issues/1638
        args: ["--config=.golangci.yaml"]
